# cloudbuild.yaml

# This file defines the steps for Google Cloud Build to create a CI/CD pipeline.
# It will build your Docker image, push it to Google Artifact Registry,
# and deploy it to Google Cloud Run.

steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    id: Build
    args:
      - 'build'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:$COMMIT_SHA'
      - '-t'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:latest'
      - '.'

  # Step 2: Push the Docker image with COMMIT_SHA tag to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Commit-SHA
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:$COMMIT_SHA'

  # Step 3: Push the Docker image with 'latest' tag to Google Artifact Registry
  - name: 'gcr.io/cloud-builders/docker'
    id: Push-Latest
    args:
      - 'push'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:latest'

  # Step 4: Deploy the image to Google Cloud Run
  - name: 'gcr.io/google.com/cloudsdk/cloud-sdk'
    id: Deploy
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - 'tnk-tryon-service' # Name of your Cloud Run service
      - '--image'
      - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:$COMMIT_SHA'
      - '--region'
      - 'asia-south1' # Ensure this matches your Artifact Registry location
      - '--platform'
      - 'managed'
      - '--allow-unauthenticated' # Temporarily allow unauthenticated for API Gateway to reach it.
                                 # API Gateway will handle authentication.
      - '--set-env-vars=GOOGLE_API_KEY_SECRET_NAME=tnk-api-key-secret' # Secret Manager secret name
      - '--update-secrets=GOOGLE_API_KEY=tnk-api-key-secret:latest' # Mount the secret as an environment variable
      - '--memory'
      - '1Gi' # Allocate 1 GB of memory
      - '--cpu'
      - '1' # Allocate 1 CPU
      - '--timeout'
      - '300s' # 5-minute timeout for requests
      - '--max-instances'
      - '3' # Maximum number of instances for scaling

# Specify the NEW service account created in Step 3, Phase 1
serviceAccount: projects/$PROJECT_ID/serviceAccounts/tnk-tryon-builder@$PROJECT_ID.iam.gserviceaccount.com

images:
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:$COMMIT_SHA'
  - 'asia-south1-docker.pkg.dev/$PROJECT_ID/tryon-repo/tnk-tryon-app:latest'
